import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/Navbar'

import React from 'react'


export const metadata: Metadata = {
  title: 'Image Gallery',
  description: 'Generated by create next app',
}

export const revalidate = 3600

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
      
      <Navbar></Navbar>
  

    
      <main className='max-w-6xl mx-auto'>
        {children}
   
      </main>
    
      </body>
    </html>
  )
}
